url: "https://marketplace.ghost.org"
encoding: UTF-8

exclude:
  - .git/
  - .github/
  - gulpfile.js
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.MD
  - LICENSE

defaults:
  -
    values:
      layout: "default"
